version: '3.8'

services:
  oms-monolith:
    extends:
      file: docker-compose.yml
      service: oms-monolith
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - PYTHONUNBUFFERED=1
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
    command: ["sh", "-c", "echo 'Starting with debug logging...' && ./start_debug.sh"]
    volumes:
      - ./oms-debug-logs:/app/logs
      - ./ontology-management-service/start_debug.sh:/app/start_debug.sh:ro