import jwt
import json

token = "eyJhbGciOiJSUzI1NiIsImtpZCI6ImtleS1lbnYtZGYyNmQ3MzgiLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiJlZWIzYjk5Ni05ZTkxLTQzOWQtYjAxMi1mYzYwNjdjZGNjM2MiLCJ1c2VyX2lkIjoiZWViM2I5OTYtOWU5MS00MzlkLWIwMTItZmM2MDY3Y2RjYzNjIiwidXNlcm5hbWUiOiJpbnRlZ3JhdGlvbl90ZXN0XzM0ODU4MyIsImVtYWlsIjoiaW50ZWdyYXRpb25fMzQ4NTgzQHRlc3QuY29tIiwidHlwZSI6ImFjY2VzcyIsImV4cCI6MTc1MjIxNTE0OSwiaWF0IjoxNzUyMjEzMzQ5LCJpc3MiOiJ1c2VyLXNlcnZpY2UiLCJhdWQiOiJvbXMiLCJraWQiOiJrZXktZW52LWRmMjZkNzM4Iiwic2lkIjoiYjVlZDg3MDQtYWUzNC00ZmFhLWIyOWYtOWQ4ZTA2M2YxZGZjIiwicm9sZXMiOlsidXNlciJdLCJzY29wZSI6ImFwaTpzY2hlbWFzOnJlYWQgYXBpOm9udG9sb2dpZXM6cmVhZCIsInNjb3BlcyI6WyJhcGk6c2NoZW1hczpyZWFkIiwiYXBpOm9udG9sb2dpZXM6cmVhZCJdLCJ0ZW5hbnRfaWQiOiJkZWZhdWx0In0.pk0D9Cuen6EuEnf_TLbrg7aEnI9TW0n2Wb1HvfDHaREKqMxHK9KtpqV9KyJzF-OmxXocYSBQ5BU2ieXosIuDXV3sHr_I-FXwLJumTjO-JGq-HOVOkyRTpFbqdcfO1FPfKCfecxLtC-FNPPrNhw_rJSZ-LT_gYBgkf5sdRwRw-kzGdBEP4yljLoosi-Yk2n3G7ShfR5hfrtZl3OrDD2mvLG2_unoLOdUGl6tyQCG_vBfkXXlrRzliw51pKMalwh4-hBS6IQd3RDPnDh9hSrqGCbOCSIhMNxI1UOpOWWXXgYdF-0T24RYuL4eC1naPoN9Mv8LDJvExEeZ8BfkgJAxjSg"

# Decode without verification to see the contents
decoded = jwt.decode(token, options={"verify_signature": False})
print(json.dumps(decoded, indent=2))