version: '3.8'

services:
  nginx-gateway:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - oms-monolith
      - user-service
      - audit-service

  audit-service:
    image: arrakis-project-audit-service
    build:
      context: ./audit-service
    environment:
      DATABASE_URL: postgresql+asyncpg://audit_user:audit_password@audit-postgres:5432/audit_db
      JWT_SECRET: your_shared_secret_key_for_all_services_with_32_chars
      JWT_AUDIENCE: oms
      JWT_ISSUER: user-service
    depends_on:
      audit-postgres:
        condition: service_healthy

  # Ontology Management Service (Monolith)
  oms-monolith:
    image: arrakis-project-oms-monolith
    build:
      context: .
      dockerfile: ontology-management-service/Dockerfile
    ports:
      - "8091:8000"  # Application port
      - "8090:8090" # TerminusDB UI port
    volumes:
      - ./ontology-management-service:/app
      - ./packages:/app/packages
    environment:
      SERVICE_NAME: oms-monolith
      ENVIRONMENT: development
      LOG_LEVEL: DEBUG
      DATABASE_URL: postgresql+asyncpg://oms_user:oms_password@oms-postgres:5432/oms_db
      REDIS_URL: redis://redis:6379/0
      TERMINUSDB_URL: http://terminusdb:6363
      TERMINUSDB_API_KEY: root
      TERMINUSDB_USER: admin
      TERMINUSDB_DB: arrakis
      JWT_SECRET: your_shared_secret_key_for_all_services_with_32_chars
      JWT_AUDIENCE: oms
      JWT_ISSUER: user-service
      USER_SERVICE_URL: http://user-service:8000
      OMS_SERVICE_URL: http://oms-monolith:8000
    depends_on:
      oms-postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      terminusdb:
        condition: service_started
    networks:
      - default

  # User Service
  user-service:
    image: arrakis-project-user-service
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8080:8000"  # User service API port
    environment:
      DATABASE_URL: postgresql+asyncpg://user_user:user_password@user-postgres:5432/user_db
      JWT_SECRET: your_shared_secret_key_for_all_services_with_32_chars
      JWT_AUDIENCE: oms
      JWT_ISSUER: user-service
      REDIS_URL: redis://redis:6379/0
      JWT_PRIVATE_KEY_BASE64: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2xBZ0VBQW9JQkFRREFUS2MvcmZqR1NUNHcKeDRZQnZ5SHdsK0xwaWU3Z1h6b0hHeVNpdFd3TDhVdHMwSUU5L2w5VHZ5QTlhL3FvdzduNEJxK0Q2VUNZQTNmMwpER3F3SDREMEhuTDMybnhhN05vam5uRGUzSjdCZm54UFdrUGRCeFZ3emZ2MmkzVXBOZzdneVdPZENvZUJ6L1d3CmhJSHhna0lpQXVQYTNDWUtER0JWejIvWUtVc2l5WXBwUzU5cGxXN1lFbHUweWxZZmUxSXIxWkVGdUU4R29xNXYKSzh3RlozT2NrSDdWbmdZMGl6VDhoajdVRkxWWFRvdTZOOFBBd2dPbG1OL1RWc3RIejdtd2lNT00xSXVaNWxKcwpBampnSlNPYUYvVEFKb0ZPUnowMERYVEhwQVRHVDFyVnJVU2owU0VkeTk3SDhWTTI3ZDBrRkVDYmozMnYzbjh4CnE0dUNaeUUzQWdNQkFBRUNnZ0VBR1IxSnV6Ylk1cE5QNmRDbnhKaExuSitjUDl6eHFPQmhuenVoSEJaRDlMRlYKcFBIOFFjdWV5VHkzdjEzWUFFSXVYN2F4SmR5emxodzBodWJhYU5oM0g5VjVpcnVWckhoWGdFOE9pd1NzUCtBVQpQY3d2cGNacGtKc2pwNDQzY0hqc3dOaDhjb09hc1U1UmdQVmxWU25WRjVwaUJodVBaT3VRaWY4aFZTS3cwSlkyCkpxNzF6bHRNSU12TUVxL0NQRUQxQjJVQW96clZSbFVScURuY2VMUlZRMVNYTExRYkxyZytIRTIxWmJyYjFpUFAKZlpmSktoS1BIOVgydFAwZXArZTYwTHRJRlJWbGUwU0FGc0crZXBLQkRUbTBEeGw4RU40bSt3WTZjei8xMjR4eQpiZHNPSGdxVkNKSUkxR0UyaGxLMGRjaXk1anVKbE5hYzdMSFlWcEl2blFLQmdRRGUzMUFtRXZ2Y2h3Tlh6cWMyCmxJMk43NWxWeTU3VXE0U01vNzgrUkFJb0ROdGdMS3BTZnJhMjYzZ25uRE5IMTYwNmxQU2VoYncxdVM0Q2w0R0kKQTZicUh3TllJL1J0NkJmbm1TTjlySlRxVWFmQWE1OXUzZmQvbnA2V1FudlhUYWY3OWxTKzVWNFNpMnYyVGhNbwpkZjhqbUZSRXBqY1krdDZZTkdQTHBQQ2p2UUtCZ1FEYzRmelFzd1doUDZZS3ZSOFZNWkxSZ25KZ1lLVEtnMmZLCkVrT1hnUVExeGIwQ3Z1TWJERE5wQWt6VnNFSXErWmkwUWliTEpjUHNSUkVCUkJ6NTcvOWxBeDZPZWtEa0hTdjkKQWlseGFRcS94aUFKMytlRkpCSWNsejhQU2NUNFFJeXNEZ0ZJU0RpcjRzM2FiNlhDdVBXelBzeFNST2ErTnZ3NwpCQWxtK01KdUF3S0JnUURXN2FKY1pWaFA3ai95RU04K21ubjhWQUNhTlhoaGZWcWhTbFJtbHExQnRFeG03Z3YrCjdFWUdGd1JUcHBYcGhYdUFFQi9yTStzeUgvZlg5Z1dyaG1JVVMzNHRKTmRXbWtsYlJscHNtdDh0TFR2S0c3K3YKNmcwQkhKV3hNRUkvZXBzeUovYkg5V2dJR0Q0d1ZGQ3paejk2TXkrbzJHWXdCOVpjRDhIaHBKbVFQUUtCZ1FDLwpPR1ZGeDdYNEFzSWNTZDIrMjB2ZlZLN3dBTHFwRjFtaTltek5uRU9veWFiMzJZbUN3TzFBMjF6cEljNG1waTRzCjM1ZjJCcHUyejVRSkpJNXhVZlFuM3F0MWJTRUFXc0RhS0NUNHFaZEVycURONjZqaStuY3ppVHh1WDg3Rm5Cd3MKVjNPRXdBRlB6T21wVVQ2UGROQkFmUDBsdThDR3E5Tnd3KzNmMXp0N1FRS0JnUUNhcE5QMDRSM1BSVzZ5cml6dApIeDZKRXpnRmRhRVFKQmZxNzN1UCt1Z0RnOWNvdU9BWUt2S1MvdHl0bkZsa3p0SFUyM1VwcnFQZldpd1JuZFltCjVIQTRzK0RpaWNLS2E2blE4NGlZVWx6ZkluSnFPaFc3eUJQbEhwaSsvcldjazcvWm5Ca3oxQll3aWdoK1IyY1kKNCtnSEN1Qm9oejNQdStTZEpHRkJIcHA5a0E9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
      JWT_PUBLIC_KEY_BASE64: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF3RXluUDYzNHhraytNTWVHQWI4aAo4SmZpNlludTRGODZCeHNrb3JWc0MvRkxiTkNCUGY1ZlU3OGdQV3Y2cU1PNStBYXZnK2xBbUFOMzl3eHFzQitBCjlCNXk5OXA4V3V6YUk1NXczdHlld1g1OFQxcEQzUWNWY00zNzlvdDFLVFlPNE1sam5RcUhnYy8xc0lTQjhZSkMKSWdMajJ0d21DZ3hnVmM5djJDbExJc21LYVV1ZmFaVnUyQkpidE1wV0gzdFNLOVdSQmJoUEJxS3VieXZNQldkegpuSkIrMVo0R05JczAvSVkrMUJTMVYwNkx1amZEd01JRHBaamYwMWJMUjgrNXNJakRqTlNMbWVaU2JBSTQ0Q1VqCm1oZjB3Q2FCVGtjOU5BMTB4NlFFeGs5YTFhMUVvOUVoSGN2ZXgvRlROdTNkSkJSQW00OTlyOTUvTWF1TGdtY2gKTndJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
    depends_on:
      user-postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Databases
  oms-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: oms_db
      POSTGRES_USER: oms_user
      POSTGRES_PASSWORD: oms_password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oms_user -d oms_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - oms_postgres_data:/var/lib/postgresql/data

  user-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_password
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_user -d user_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - user_postgres_data:/var/lib/postgresql/data

  audit-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: audit_db
      POSTGRES_USER: audit_user
      POSTGRES_PASSWORD: audit_password
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U audit_user -d audit_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - audit_postgres_data:/var/lib/postgresql/data

  terminusdb:
    image: terminusdb/terminusdb-server:latest
    ports:
      - "6363:6363"
    environment:
      TERMINUSDB_ADMIN_PASSWORD: root

  # Other services
  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"

networks:
  default:
    driver: bridge

volumes:
  oms_postgres_data:
  user_postgres_data:
  audit_postgres_data: