alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
global:
  evaluation_interval: 15s
  external_labels:
    environment: production
    monitor: oms-cluster
  scrape_interval: 15s
rule_files:
- /etc/prometheus/rules/*.yml
- /etc/prometheus/rules/enterprise_resilience_alerts.yml
scrape_configs:
- job_name: user-service
  metrics_path: /metrics
  scrape_interval: 5s
  static_configs:
  - targets:
    - host.docker.internal:8012
- job_name: oms-service
  metrics_path: /metrics
  scrape_interval: 5s
  static_configs:
  - targets:
    - host.docker.internal:8010
- job_name: audit-service
  metrics_path: /metrics
  scrape_interval: 5s
  static_configs:
  - targets:
    - host.docker.internal:8011
- job_name: node-exporter
  static_configs:
  - targets:
    - localhost:9100
- job_name: redis-exporter
  static_configs:
  - targets:
    - localhost:9121
- job_name: postgres-exporter
  static_configs:
  - targets:
    - localhost:9187
- job_name: jaeger
  static_configs:
  - targets:
    - localhost:14269
