# TechDocs configuration for Data Kernel Service
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: data-kernel-service
  description: Centralized gateway for TerminusDB operations with validation hooks
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: data-platform-team

techdocs:
  builder: "local"
  generator:
    runIn: "local"
  publisher:
    type: "local"

build:
  dependencies:
    - python: ">=3.9"
    - terminusdb: "latest"
    - grpcio: ">=1.50"
    - opentelemetry: "latest"

documentation:
  structure:
    - name: Overview
      path: docs/README.md
    - name: API Reference
      items:
        - name: REST API
          path: docs/api/rest.md
        - name: gRPC API
          path: docs/api/grpc.md
        - name: Validation Hooks
          path: docs/api/hooks.md
        - name: Query Interface
          path: docs/api/queries.md
    - name: Data Model
      items:
        - name: Schema Design
          path: docs/data/schema.md
        - name: Graph Operations
          path: docs/data/graph.md
        - name: WOQL Queries
          path: docs/data/woql.md
        - name: Data Pipelines
          path: docs/data/pipelines.md
    - name: Architecture
      items:
        - name: System Design
          path: docs/architecture/system-design.md
        - name: Hook System
          path: docs/architecture/hooks.md
        - name: Caching Strategy
          path: docs/architecture/caching.md
        - name: Integration Patterns
          path: docs/architecture/integrations.md
    - name: Operations
      items:
        - name: Deployment Guide
          path: docs/ops/deployment.md
        - name: TerminusDB Management
          path: docs/ops/terminusdb.md
        - name: Performance Tuning
          path: docs/ops/performance.md
        - name: Troubleshooting
          path: docs/ops/troubleshooting.md
    - name: Development
      items:
        - name: Setup Guide
          path: docs/dev/setup.md
        - name: Writing Hooks
          path: docs/dev/hooks.md
        - name: Testing Strategies
          path: docs/dev/testing.md
        - name: Contributing
          path: docs/dev/contributing.md
