global:
  smtp_smarthost: "localhost:587"
  smtp_from: "alerts@example.com"

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "web.hook"

receivers:
  - name: "web.hook"
    webhook_configs:
      - url: "http://localhost:9093/api/v1/alerts"
        send_resolved: true
