# ARRAKIS PROJECT - UNIFIED PROMETHEUS CONFIGURATION
# =================================================
# 모든 중복 설정을 통합한 최종 버전
# Last Updated: 2025-07-12

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "arrakis-production"
    environment: "production"

# Alertmanager 설정
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - host.docker.internal:9093 # Alertmanager

# 알람 규칙 파일
rule_files:
  - "/etc/prometheus/rules/*.yml"

# 스크랩 설정
scrape_configs:
  # ========== CORE MSA SERVICES (현재 실행 중) ==========
  - job_name: "user-service"
    static_configs:
      - targets: ["host.docker.internal:8012"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "oms-service"
    static_configs:
      - targets: ["host.docker.internal:8010"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "audit-service"
    static_configs:
      - targets: ["host.docker.internal:8011"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  # ========== EXPORTERS ==========
  - job_name: "node-exporter"
    static_configs:
      - targets: ["host.docker.internal:9100"]
    metrics_path: "/metrics"
    scrape_interval: 15s

  - job_name: "redis-exporter"
    static_configs:
      - targets: ["host.docker.internal:9121"]
    metrics_path: "/metrics"
    scrape_interval: 15s

  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["host.docker.internal:9187"]
    metrics_path: "/metrics"
    scrape_interval: 15s

  # ========== MONITORING INFRASTRUCTURE ==========
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "alertmanager"
    static_configs:
      - targets: ["host.docker.internal:9093"]

  - job_name: "grafana"
    static_configs:
      - targets: ["host.docker.internal:3000"]

  # ========== TRACING & PROFILING ==========
  - job_name: "jaeger"
    static_configs:
      - targets: ["host.docker.internal:14269"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  # ========== CUSTOM SERVICES ==========
  - job_name: "alerting-webhook"
    static_configs:
      - targets: ["host.docker.internal:8080"]
    metrics_path: "/health"
    scrape_interval: 30s

  # ========== FUTURE SERVICES (준비됨) ==========
  # Real Services (활성화 시 주석 해제)
  #- job_name: 'user-service-real'
  #  static_configs:
  #  - targets: ['host.docker.internal:8080']
  #
  #- job_name: 'oms-monolith-real'
  #  static_configs:
  #  - targets: ['host.docker.internal:8091']
  #
  #- job_name: 'audit-service-real'
  #  static_configs:
  #  - targets: ['host.docker.internal:8092']
