# TechDocs configuration for Embedding Service
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: embedding-service
  description: Vector embedding and similarity service with semantic search capabilities
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: ml-platform-team

techdocs:
  builder: "local"
  generator:
    runIn: "local"
  publisher:
    type: "local"

build:
  dependencies:
    - python: ">=3.9"
    - sentence-transformers: ">=2.0"
    - torch: ">=1.13"
    - grpcio: ">=1.50"
    - faiss: ">=1.7"

documentation:
  structure:
    - name: Overview
      path: docs/README.md
    - name: API Reference
      items:
        - name: REST API
          path: docs/api/rest.md
        - name: gRPC API
          path: docs/api/grpc.md
        - name: Batch Processing
          path: docs/api/batch.md
        - name: Similarity Search
          path: docs/api/similarity.md
        - name: Vector Operations
          path: docs/api/vectors.md
    - name: Models
      items:
        - name: Supported Models
          path: docs/models/supported.md
        - name: Model Configuration
          path: docs/models/config.md
        - name: Performance Comparison
          path: docs/models/performance.md
        - name: Model Updates
          path: docs/models/updates.md
    - name: Architecture
      items:
        - name: System Design
          path: docs/architecture/system-design.md
        - name: Vector Storage
          path: docs/architecture/storage.md
        - name: Indexing Strategy
          path: docs/architecture/indexing.md
        - name: Caching Layer
          path: docs/architecture/caching.md
    - name: Operations
      items:
        - name: Deployment Guide
          path: docs/ops/deployment.md
        - name: Model Management
          path: docs/ops/models.md
        - name: Scaling Guide
          path: docs/ops/scaling.md
        - name: Monitoring
          path: docs/ops/monitoring.md
        - name: Troubleshooting
          path: docs/ops/troubleshooting.md
    - name: Development
      items:
        - name: Setup Guide
          path: docs/dev/setup.md
        - name: Model Integration
          path: docs/dev/model-integration.md
        - name: Testing Strategies
          path: docs/dev/testing.md
        - name: Contributing
          path: docs/dev/contributing.md
